import TopologicalAlignment.Definitions
import TopologicalAlignment.Empowerment
import TopologicalAlignment.Viability
import TopologicalAlignment.RobustDominance
import TopologicalAlignment.RelationalViability
import TopologicalAlignment.MoralGoodness
